### ISSUE TITLE
No module named pipes in Python 3.13

### ISSUE THREAD

**Issue by thelabcat** [grigi/talkey#11]
```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import talkey
  File "/home/wilbur/.local/lib/python3.13/site-packages/talkey/__init__.py", line 4, in <module>
    from .tts import Talkey, enumerate_engines, create_engine, TTSError
  File "/home/wilbur/.local/lib/python3.13/site-packages/talkey/tts.py", line 3, in <module>
    from .base import TTSError
  File "/home/wilbur/.local/lib/python3.13/site-packages/talkey/base.py", line 2, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```

**Comment by thelabcat** [comment]
Cause: [The pipes library](https://pypi.org/project/standard-pipes/) is considered a 'dead battery' and has been removed from standard Python.
Workaround: `pip install standard-pipes`
